name = "qiuyuan-blog"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2026-02-14"
compatibility_flags = ["nodejs_compat"]

[env.production]
compatibility_flags = ["nodejs_compat"]

[env.preview]
compatibility_flags = ["nodejs_compat"]
